from typing import overload

__all__ = [
    "Decoder",
    "MDR",
    "QRNG",
    "CRC",
    "statistics",
    "print",
    "binary_to_bipolar",
    "get_LLR",
    "get_CRC_values",
    "check_CRC",
    "calculate_syndrome",
    "reconcile",
    "read_quantum_states",
    "capacity",
    "snr_from_capacity",
]

class Decoder:
    def __init__(
        self,
        NoI: int = 500,
        layered_flag: bool = True,
        fast_flag: bool = True,
        H_file_name: str = "R_0p2_R_0p01_RA_SPPCOM_2",
        lifting_factor: int = 5000,
        print_flag: bool = False,
    ) -> None: ...
    def get_N(self) -> int: ...
    def get_M(self) -> int: ...
    def set_rate(self, rate: float) -> None: ...
    def get_rate(self) -> float: ...
    def get_syndrome(self, word: list[int]) -> list[int]: ...
    def SPA_decoder(
        self, llr_in: list[float], syndrome: list[int]
    ) -> tuple[list[int], int, bool]: ...
    def get_decoding_error_count(self, decoded: list[int], true: list[int]) -> int: ...

class MDR:
    def __init__(self, dim: int = 8, print_flag: bool = False) -> None: ...
    def normalize(self, x: list[float]) -> list[float]: ...
    def multiplication_Alice(
        self, channel_message: list[float], q_states: list[float]
    ) -> list[float]: ...
    def multiplication_Bob(
        self, received_quantum_states: list[float], QRNG_output_bipolar: list[float]
    ) -> list[float]: ...

class QRNG:
    def __init__(self, seq_length: int, NoF: int, print_flag: bool = False) -> None: ...
    def generate_random_sequence(self) -> list[list[int]]: ...

class CRC:
    def __init__(self, polynomial: int = 0xEDB88320) -> None: ...
    def get_CRC_checksum(self, data: list[int]) -> list[int]: ...

class statistics:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self, blocklength: int, num_of_frames: int, MDR_dim: int, crc_length: int
    ) -> None: ...
    def set_rate(self, rate: float) -> None: ...
    def set_num_of_quantum_states(self, n: int) -> None: ...
    def set_number_of_unused_states(self, n: int) -> None: ...
    def set_bit_error_count(self, frame_index: int, count: float) -> None: ...
    def set_frame_error_count(self, frame_index: int) -> None: ...
    def set_num_of_iterations(self, frame_index: int, iterations: float) -> None: ...
    def mark_codeword_as_wrong(self, frame_index: int) -> None: ...
    def set_count_of_undetectable_error_after_CRC(self, n: int) -> None: ...
    def set_count_of_wrong_codewords_detected_by_CRC(self, n: int) -> None: ...
    def start_timing(self) -> None: ...
    def end_timing(self) -> None: ...
    def get_count_of_undetectable_error_after_CRC(self) -> int: ...
    def get_count_of_wrong_codewords_detected_by_CRC(self) -> int: ...
    def get_elapsed_time(self) -> float: ...
    def get_average_time(self) -> float: ...
    def get_bit_error_count(self, frame_index: int) -> float: ...
    def get_frame_error_count(self, frame_index: int) -> int: ...
    def get_num_of_iterations(self, frame_index: int) -> float: ...
    def get_bit_error_rate(self) -> float: ...
    def get_frame_error_rate(self) -> float: ...
    def get_average_num_of_iterations(self) -> float: ...
    def get_total_frame_error_count(self) -> int: ...
    def get_num_of_decoding_frames(self) -> int: ...
    def get_count_of_wrong_codewords(self) -> int: ...
    def get_total_number_of_states(self) -> int: ...
    def get_number_of_unused_states(self) -> int: ...
    def get_rate(self) -> float: ...
    def get_blocklength(self) -> int: ...
    def get_crc_length(self) -> int: ...
    def get_MDR_dim(self) -> int: ...
    def get_noise_variance(self) -> float: ...
    def set_noise_variance(self, variance: float) -> None: ...
    def get_layered_flag(self) -> int: ...
    def get_average_statistics(
        self,
    ) -> tuple[float, float, int, int, int, float, float, float]: ...
    def __add__(self, other: statistics) -> statistics: ...

class print:
    def __init__(self, flag: bool = True) -> None: ...
    def print_statistics_report(self, stats: statistics) -> None: ...

def binary_to_bipolar(
    QRNG_output: list[list[int]],
    N: int,
    num_of_decoding_frames: int,
    MDR_dim: int = 8,
) -> list[float]: ...

def get_LLR(
    synthetic_channel_output: list[float],
    alice_normalization_vector: list[float],
    bob_normalization_vector: list[float],
    noise_variance: float,
    MDR_dim: int,
    num_of_decoding_frames: int,
    N: int,
    print_flag: bool = False,
) -> list[list[float]]: ...

def get_CRC_values(
    decoded_frame: list[list[int]],
    crc: CRC,
    num_of_decoding_frames: int,
) -> list[list[int]]: ...

def check_CRC(
    CRC_decoded: list[list[int]],
    CRC_QRNG: list[list[int]],
    syndrome_flags: list[int],
    stats: statistics,
    num_of_decoding_frames: int,
    print_flag: bool = False,
) -> tuple[float, int]: ...

def calculate_syndrome(
    LDPC_decoder: Decoder,
    QRNG_output: list[list[int]],
    num_of_decoding_frames: int,
    print_flag: bool = False,
) -> list[list[int]]: ...

def reconcile(
    alice_states: list[float],
    bob_states: list[float],
    rate: float,
    noise_variance: float,
    NoI: int = 500,
    MDR_dim: int = 8,
    layered_decoding: bool = True,
    fast_decoding: bool = True,
    print_flag: bool = False,
    H_file_name: str = "R_0p2_R_0p01_RA_SPPCOM_2",
    lifting_factor: int = 5000,
) -> statistics: ...

def read_quantum_states(filename: str) -> list[float]: ...
def capacity(snr: float) -> float: ...
def snr_from_capacity(capacity: float) -> float: ...
