name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: ../IR_for_CVQKD/conda/environment.yml
          activate-environment: IR_lib
          auto-update-conda: false
          auto-activate-base: false
          
      - name: create the build directory
        shell: bash -el {0}
        run: |
          cd IR_lib
          
      - name: "Create build directory and run CMake"
        shell: bash -el {0}
        run: cmake -S . -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
      - name: "Build Project"
        shell: bash -el {0}
        run: cmake --build build --target all --config Release -- -j4 

        
          
